name: movie_night_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  
  provider:
  flutter_animate: ^4.3.0
  transparent_image: ^2.0.1
  http: ^1.1.0
  carousel_slider: ^4.2.1
  device_info_plus: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
    


  # http: ^1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 700
